name: Go CI
on:
    push:
        branches: [ main ]
jobs:
    build:
        name: Build
        strategy:
            matrix:
                go-version: [ 1.19.x, 1.20.x ]
                platform: [ macos-latest, ubuntu-latest, windows-latest ]
        runs-on: ${{ matrix.platform }}
        steps:
            -   name: Set up Go ${{matrix.go-version}}
                uses: actions/setup-go@v3
                with:
                    go-version: ${{matrix.go-version}}
            -   name: Check out code
                uses: actions/checkout@v3
            -   name: Test
                run: |
                    go clean -testcache
                    go test -v ./...
                shell: bash
# Add golint and go vet to the pipeline